language: node_js
node_js:
  - "8"
script:
  - echo 'Deploy!!'
  - echo 'Installing Deps!'
  - yarn
  - cd functions
  - yarn
  - cd ..
  - echo 'Building!'
  - npm run build:release
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
